#fonts
font=PxPlus IBM VGA8:style=Regular:size=12
[colors-dark]
background=000000
foreground=cccccc

selection-background=000080
selection-foreground=ffffff

regular0=000000
regular1=800000
regular2=008000
regular3=808000
regular4=000080
regular5=800080
regular6=008080
regular7=c0c0c0

## Bright
bright0=808080
bright1=ff0000
bright2=00ff00
bright3=ffff00
bright4=0000ff
bright5=ff00ff
bright6=00ffff
bright7=ffffff

